export const CANDLE_PANE_ID = 'candle_pane'
export const VOLUME_PANE_ID = 'volume_pane'
export const MACD_PANE_ID = 'macd_pane'
export const RSI_PANE_ID = 'rsi_pane'
export const KDJ_PANE_ID = 'kdj_pane'
export const ATR_PANE_ID = 'atr_pane'
export const RETAIL_HEAT_PANE_ID = 'retail_heat_pane'
